# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
        # Trims trailing whitespace
    -   id: trailing-whitespace
        # Makes sure files end in a newline and only a newline
    -   id: end-of-file-fixer
