sudo: required
dist: trusty
language: node_js
cache: yarn
node_js: 10
before_install:
# Use newer yarn than that pre-installed in the Travis image.
- curl -sSfL https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --frozen-lockfile
script:
- yarn build
deploy:
  provider: script
  email: '$NPM_EMAIL'
  on:
    branch: master
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  script:
  - yarn semantic-release
