steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - DOCKER_FLOW_VERSION=${_VERSION}
      - '-t'
      - ${_IMAGE_NAME}:${_IMAGE_VERSION}
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE_NAME}:${_IMAGE_VERSION}
    id: Push
  - name: bash
    args:
      - '-c'
      - echo "$$DEV_CONFIG" > /workspace/dev-config.yml && echo "$$INGRESS" > /workspace/infrastructure/k8s/templates/ingress.yaml
    id: Get secrets
    secretEnv:
      - DEV_CONFIG
      - INGRESS
  - name: node:${_NODE_VERSION}
    args:
      - '-c'
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && apt-get update -y && apt-get install google-cloud-cli google-cloud-sdk-gke-gcloud-auth-plugin -y && gcloud container clusters get-credentials ${PROJECT_ID} --region us-east1 --project ${PROJECT_ID} && yarn && yarn dev:db:upgrade && yarn dev:apply
    id: Deploy
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - gcloud container images list-tags ${_IMAGE_NAME} --filter='-tags:*' --format='get(digest)' --limit=unlimited | xargs -I {sha} gcloud container images delete "${_IMAGE_NAME}@{sha}"
    id: Delete old images
    entrypoint: bash
timeout: 1800s
images:
  - ${_IMAGE_NAME}:${_IMAGE_VERSION}
options:
  dynamicSubstitutions: true
substitutions:
  _NODE_VERSION: 16.16.0
  _VERSION: '{"version":"${BRANCH_NAME}_dev","commit":"${SHORT_SHA}","source":"https://github.com/taskcluster/taskcluster","build":"${BUILD_ID}"}'
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/${PROJECT_ID}/${BRANCH_NAME}
  _IMAGE_VERSION: latest
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/dev-config/versions/latest
      env: DEV_CONFIG
    - versionName: projects/${PROJECT_ID}/secrets/ingress/versions/latest
      env: INGRESS
