[package]
name = "taskcluster-download"
version = "42.0.0"
authors = ["Dustin J. Mitchell <dustin@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Taskcluster Download Support"

[dependencies]
taskcluster = { path = "../client" }
anyhow = "1.0"
async-trait = "0.1"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde_json = "1.0.48"
tokio = { version = "1.2", features = ["macros", "time", "fs"] }
tokio-util = { version = "0.6", features = ["codec", "io"] }
futures-util = "0.3"

[dev-dependencies]
httptest = "^0.15.1"
tempfile = "3"
