---
trust-domain: taskcluster
# this is lower priority than the decision task
task-priority: high

taskgraph:
  register: src:register
  repositories:
    taskcluster:
      name: taskcluster

workers:
  aliases:
    ci:
      provisioner: proj-taskcluster
      os: linux
      implementation: docker-worker
      worker-type: ci
    release:
      provisioner: proj-taskcluster
      os: linux
      implementation: generic-worker
      worker-type: release
    gw-ubuntu-22-04:
      provisioner: proj-taskcluster
      os: linux
      implementation: generic-worker
      worker-type: gw-ubuntu-22-04
    gw-windows-2022:
      provisioner: proj-taskcluster
      os: windows
      implementation: generic-worker
      worker-type: gw-windows-2022
