apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskcluster-ingress
  labels:
    app.kubernetes.io/name: taskcluster-ingress
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-ingress-ingress
    app.kubernetes.io/part-of: taskcluster
  annotations:
    kubernetes.io/ingress.global-static-ip-name: '{{ .Values.ingressStaticIpName }}'
    ingress.gcp.kubernetes.io/pre-shared-cert: '{{ .Values.ingressCertName }}'
spec:
  rules:
    - host: '{{ substr 8 -1 (trimSuffix "/" .Values.rootUrl) }}'
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-ui
                port:
                  number: 80
          - path: /references
            pathType: Prefix
            backend:
              service:
                name: taskcluster-references
                port:
                  number: 80
          - path: /references/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-references
                port:
                  number: 80
          - path: /schemas
            pathType: Prefix
            backend:
              service:
                name: taskcluster-references
                port:
                  number: 80
          - path: /schemas/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-references
                port:
                  number: 80
          - path: /api/auth/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-auth
                port:
                  number: 80
          - path: /api/github/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-github
                port:
                  number: 80
          - path: /api/hooks/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-hooks
                port:
                  number: 80
          - path: /api/index/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-index
                port:
                  number: 80
          - path: /api/notify/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-notify
                port:
                  number: 80
          - path: /api/object/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-object
                port:
                  number: 80
          - path: /api/purge-cache/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-purge-cache
                port:
                  number: 80
          - path: /api/queue/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-queue
                port:
                  number: 80
          - path: /api/secrets/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-secrets
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: taskcluster-web-server
                port:
                  number: 80
          - path: /login/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-web-server
                port:
                  number: 80
          - path: /subscription
            pathType: Prefix
            backend:
              service:
                name: taskcluster-web-server
                port:
                  number: 80
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: taskcluster-web-server
                port:
                  number: 80
          - path: /api/web-server/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-web-server
                port:
                  number: 80
          - path: /api/worker-manager/*
            pathType: Prefix
            backend:
              service:
                name: taskcluster-worker-manager
                port:
                  number: 80
