apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-worker-manager-workerscannerazure
  labels: &ref_0
    app.kubernetes.io/name: taskcluster-worker-manager
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-worker-manager-workerscannerazure
    app.kubernetes.io/part-of: taskcluster
spec:
  replicas: {{ int (.Values.worker_manager.procs.workerscannerAzure.replicas) }}
  selector:
    matchLabels: *ref_0
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-worker-manager-secret.yaml") . | sha256sum }}'
      labels: *ref_0
    spec:
      serviceAccountName: taskcluster-worker-manager
      containers:
        - name: taskcluster-worker-manager-workerscannerazure
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - worker-manager/workerscannerAzure
          resources:
            requests:
              cpu: '{{ .Values.worker_manager.procs.workerscannerAzure.cpu }}'
              memory: '{{ .Values.worker_manager.procs.workerscannerAzure.memory }}'
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            - name: USE_KUBERNETES_DNS_SERVICE_DISCOVERY
              value: '{{ .Values.useKubernetesDnsServiceDiscovery }}'
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: taskcluster-worker-manager
          ports: []
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - exit $(awk 'BEGIN{srand(); print (rand() > 0.3)}')
            initialDelaySeconds: 86400
            periodSeconds: 60
            failureThreshold: 1
