apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-object-cleanup-expire-objects
  labels: &ref_0
    app.kubernetes.io/name: taskcluster-object
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-object-cleanup-expire-objects
    app.kubernetes.io/part-of: taskcluster
spec:
  concurrencyPolicy: Forbid
  schedule: 0 0 * * *
  jobTemplate:
    metadata:
      labels: *ref_0
    spec:
      activeDeadlineSeconds: 86340
      template:
        metadata:
          labels: *ref_0
        spec:
          restartPolicy: OnFailure
          containers:
            - name: taskcluster-object-cleanup-expire-objects
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - object/cleanup-expire-objects
              resources:
                requests:
                  cpu: '{{ .Values.object.procs.cleanup_expire_objects.cpu }}'
                  memory: '{{ .Values.object.procs.cleanup_expire_objects.memory }}'
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
                - name: USE_KUBERNETES_DNS_SERVICE_DISCOVERY
                  value: '{{ .Values.useKubernetesDnsServiceDiscovery }}'
                - name: NODE_ENV
                  value: production
              envFrom:
                - secretRef:
                    name: taskcluster-object
